name: Build and Release

# This builds the project for Windows and Android, then creates a GitHub release
# with the built artifacts whenever:
# - a tag matching 'v*' is pushed in any branch, or
# - a branch matching 'release-v*' is pushed.

on:
  push:
    tags:
      - 'v*'
    branches:
      - 'release-v*'

permissions:
  contents: write  # Required to create releases
  packages: read   # May be needed for some operations

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        build-type:
          - name: "sideload"
            build-params: "/p:PublishUnsignedPackage=true"
            output-dir: "publish/"
            artifact-dir: "artifacts/"
            artifact-name: "HouzLinc-Windows"
            file-suffix: ""
          - name: "store"
            build-params: "/p:BuildForStore=true"
            output-dir: "publish-store/"
            artifact-dir: "artifacts-store/"
            artifact-name: "HouzLinc-Windows-Store"
            file-suffix: "-Store"
    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install uno-check
        run: dotnet tool install --global uno.check

      - name: Run uno-check
        run: uno-check --ci --non-interactive --fix --skip xcode --skip androidsdk --skip androidemulator
        continue-on-error: true

      - name: Restore .NET workloads
        run: dotnet workload restore
        working-directory: UnoApp

      - name: Restore packages
        run: msbuild /r /t:Restore /p:Configuration=Release /p:PublishReadyToRun=true
        working-directory: UnoApp

      - name: Build ${{ matrix.build-type.name }} MSIX package
        run: msbuild /p:TargetFramework=net9.0-windows10.0.26100 /p:Configuration=Release /p:Platform=x64 ${{ matrix.build-type.build-params }} /p:AppxPackageDir="${{ matrix.build-type.output-dir }}"
        working-directory: UnoApp

      - name: Prepare and rename ${{ matrix.build-type.name }} artifact
        run: |
          # Create staging directory
          New-Item -ItemType Directory -Path "${{ matrix.build-type.artifact-dir }}" -Force
          
          # Find the generated MSIX file(s)
          $msixFiles = Get-ChildItem -Path "${{ matrix.build-type.output-dir }}" -Recurse -Include "*.msix"
          if ($msixFiles.Count -eq 0) {
            Write-Host "No MSIX files found for ${{ matrix.build-type.name }}!"
            exit 1
          }
          
          # Copy and rename: replace "UnoApp" with "HouzLinc" and add suffix if needed
          foreach ($sourceFile in $msixFiles) {
            $originalName = $sourceFile.Name
            $newFileName = $originalName -replace "UnoApp", "HouzLinc${{ matrix.build-type.file-suffix }}"
            $destPath = "${{ matrix.build-type.artifact-dir }}/$newFileName"
            
            Write-Host "Renaming '$originalName' to '$newFileName'"
            Copy-Item $sourceFile.FullName -Destination $destPath
          }
          
          # Show what we created
          Write-Host "Created ${{ matrix.build-type.name }} artifacts:"
          Get-ChildItem "${{ matrix.build-type.artifact-dir }}" | Format-Table Name, Length
        working-directory: UnoApp
        shell: pwsh

      - name: Upload ${{ matrix.build-type.name }} artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.build-type.artifact-name }}
          path: UnoApp/${{ matrix.build-type.artifact-dir }}*.msix

  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install uno-check
        run: dotnet tool install --global uno.check

      - name: Run uno-check
        run: uno-check --ci --non-interactive --fix --skip xcode --skip winui --skip winsdk --skip vswin --skip vsmac
        continue-on-error: true

      - name: Restore .NET workloads
        run: dotnet workload restore
        working-directory: UnoApp

      - name: Build and publish Android APK
        run: dotnet publish -f net9.0-android -c Release -o ./publish
        working-directory: UnoApp

      - name: Upload Android artifact
        uses: actions/upload-artifact@v4
        with:
          name: HouzLinc-Android
          path: UnoApp/publish/*.apk

  create-release:
    needs: [build-windows, build-android]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')  # Only create release for tags
    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: HouzLinc-Windows
          path: ./artifacts/windows

      - name: Download Microsoft Store artifact
        uses: actions/download-artifact@v4
        with:
          name: HouzLinc-Windows-Store
          path: ./artifacts/windows-store

      - name: Download Android artifact
        uses: actions/download-artifact@v4
        with:
          name: HouzLinc-Android
          path: ./artifacts/android

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./artifacts/windows/*.msix
            ./artifacts/windows-store/*.msix
            ./artifacts/android/*.apk
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
